/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "a little bit faster.": "稍微快一点。",
    "A-Challenges": "A-挑战",
    "A-Increments": "A-递增",
    "Ascension": "转生",
    "Ascension Points": "转生点",
    "At": "在",
    "Auto Increment": "自动递增",
    "Auto Prestige": "自动声望",
    "Automation": "自动化",
    "Boosts": "提升",
    "Disabled": "已禁用",
    "Enabled": "已启用",
    "False": "否",
    "Goal": "目标",
    "Unlock": "解锁",
    "unlocked": "已解锁",
    "Upgrades": "升级",
    "rewards": "奖励",
    "Reset": "重置",
    "Remove upgrade's": "移除升级",
    "Prestige": "声望",
    "Prestige Points per second": "声望点每秒",
    "Options": "选项",
    "Locked": "未解锁",
    "Mastery": "精通",
    "Next": "下一个",
    "Next Automate unlocks in": "下一个自动化解锁于",
    "Next Increment unlocks in": "下一个递增解锁于",
    "Next Pincrement unlocks in": "下一个增量解锁于",
    "Note: The game is no longer recieving updates. Try out Incrementalist": "注意：游戏不再接收更新。 请尝试《增量主义》",
    "Increments": "递增",
    "Exit Challenge": "退出挑战",
    "Fastest Ascension": "最快的转生",
    "Fastest Prestige": "最快的声望",
    "Gain Increment": "收益递增",
    "Here": "这里",
    "Error": "错误",
    "Cost": "成本",
    "Confirm Reset": "确认重置",
    "Confirm Prestige": "确认声望",
    "Confirm Challenge": "确认挑战",
    "Confirm Ascend": "确认转生",
    "Complete Challenge": "完成挑战",
    "Cannot buy or unlock Increments": "无法购买或解锁递增",
    "Ascend": "转生",
    "Scaling": "比例",
    "Toggle": "切换",
    "Toggle Automation": "切换自动化",
    "Toggle Stats": "切换统计",
    "Toggle Unlocks": "切换解锁",
    "Total Ascension Points": "总计转生点",
    "Total Increment": "总递增",
    "Total Increment this Prestige": "本次声望总递增",
    "Total Prestige Points this Ascension": "本次转生总声望点",
    "Total Prestige Points": "总声望点",
    "Translated to": "转换为",
    "Translated to a": "转换为一个",
    "Upgrades are disabled": "升级被禁用",
    "You are gaining": "你获得了",
    "Refund Upgrades on next Prestige": "退款升级在下一个声望",
    "Automation is disabled": "自动化已禁用",
    "Boost Automation": "提升自动化",
    "Boost Challenge": "提升挑战",
    "Boost Increments": "提升递增",
    "Boost PP Boost": "提升声望点提升",
    "Boost Scaling": "提升比例",
    "But increase cost scaling": "但增加成本比例",
    "Buy": "购买",
    "Can't get the game to load?": "无法加载游戏？",
    "Increment": "递增",
    "Export your save and report it to the devs by joining the discord.": "导出你的保存，并通过加入Discord报告给开发人员。",
    "Keep Auto Increment": "保留自动递增",
    "Keep Automation": "保留自动化",
    "Keep Increments": "保留递增",
    "Keep Scaling levels": "保留比例等级",
    "Master Automation": "掌握自动化",
    "Master Increments": "掌握递增",
    "Master Layer": "掌握层",
    "Master Scaling": "掌握比例",
    "negative effects": "负面影响",
    "on Prestige": "在声望上",
    "on Ascension": "在转生上",
    "/sec": "/秒",
    "AP gained on Ascension": "转生时获得的转生点",
    "Increment 1 levels on Prestige": "声望增加 1 级递增",
    "Increment Boost": "递增提升",
    "Increment Boosts": "递增提升",
    "Increment per second": "递增每秒",
    "Increment's costs have been modified": "递增的成本已被修改",
    "Increments increase the cost of other Increments": "递增会增加其他递增的成本",
    "multiplier to Increment": "乘数到递增",
    "multiplier to Prestige Points": "乘数到声望点",
    "P-Challenges": "P-挑战",
    "P-Increments": "P-递增",
    "Passive boost from AP": "来自转生点的被动提升",
    "Passive boost from PP": "来自声望点的被动提升",
    "PP": "声望点",
    "PP gained on Prestige": "声望获得的声望点",
    "PP on Prestige": "声望的声望点",
    "Prestige Boosts": "声望提升",
    "Prestige Points": "声望点",
    "Reward: Autobuyers are": "奖励：自动购买者",
    "Reward: Challenge 1, 2, 3": "奖励: 挑战 1, 2, 3",
    "Reward: Decrease the cost of Increments": "奖励：降低递增成本",
    "Reward: Lower the prestige requirement": "奖励：降低声望要求",
    "Reward: Upgrades gain another level.": "奖励：升级获得另一个等级。",
    "rewards are 2x better": "奖励提高 2 倍",
    "Gain Increment": "增益增量",
    "Auto Increment on Prestige": "声望自动增加",
    "Auto Increment 1 buys at 10": "自动递增 1 购买按 10",
    "Auto Increment 1 buys at 100": "自动递增 1 购买按 100",
    "Infinite Time": "无限时间",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Version ": "版本 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e\+([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Auto Increment (.+) on Prestige$/, '声望自动递增 $1'],
    [/^([\d\.]+) Minutes (.+) Seconds$/, '$1分钟 $2秒'],
    [/^([\d\.]+) Hours (.+) Seconds$/, '$1小时 $2秒'],
    [/^([\d\.]+) Days (.+) Hours (.+) Minutes (.+) Seconds$/, '$1天 $2小时 $3分钟 $4秒'],
    [/^(.+) Years (.+) Days (.+) Hours (.+) Minutes (.+) Seconds$/, '$1年 $2天 $3小时 $4分钟 $5秒'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^Auto increment ([\d\.]+) buys at ([\d\.]+)$/, '自动递增 $1 购买在 $2'],
	[/^Challenge ([\d\.]+)$/, '挑战 $1'],
	[/^Upgrade ([\d\.]+)$/, '升级 $1'],
	[/^Prestige Boost ([\d\.]+)$/, '声望提升 $1'],
	[/^Inc Boost ([\d\.]+)$/, '递增提升 $1'],
	[/^Scale Increment ([\d\.]+)$/, '比例递增 $1'],
	[/^Upgrade Increment ([\d\.]+)$/, '升级递增 $1'],
	[/^Increment ([\d\.]+)$/, '递增 $1'],
	[/^Keep Auto Increment ([\d\.]+)$/, '保持自动递增 $1'],
	[/^Upgrade Increment ([\d\.]+)$/, '升级递增 $1'],
	[/^Pincrement ([\d\.]+)$/, '增量 $1'],
	[/^Auto Increment ([\d\.]+)$/, '自动递增 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) Seconds$/, '$1 秒'],
	[/^([\d\.]+) PP$/, '$1 声望点'],
	[/^Decrease Increment (.+)\'s cost scaling$/, '减少递增 $1 的成本比例'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) AP$/, '成本：$1 转生点'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);